-- Q1. What is the total revenue generated by male vs. female customers?
	SELECT 
	gender,
	SUM(purchase_amount) as revenue
	from customer
	group by gender
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
	select customer_id, purchase_amount
	from customer
	where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
-- Q3. Which are the top 5 products with the highest average review rating?
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
	Select shipping_type,
	ROUND (AVG(purchase_amount), 2)
	from customer
	where shipping_type in ('Standard', 'Express')
	group by shipping_type
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(CAST(purchase_amount AS numeric)), 2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT top 5
    item_purchased,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
	with customer_type AS (
		SELECT
			customer_id,
			previous_purchases,
		CASE
			WHEN previous_purchases = 1 then 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
			End as customer_segment
			From customer
	)
	SELECT 
		customer_segment,
		COUNT(*) as number_of_customers
	FROM customer_type
	group by customer_segment;
-- Q8. What are the top 3 most purchased products within each category?
	with item_counts as (
	select category,
	item_purchased,
	COUNT(customer_id) as total_oders,
	ROW_NUMBER() OVER(partition by category order by count(customer_id) DESC) as item_rank from customer
	group by category, item_purchased
	)
	select item_rank, category, item_purchased, total_oders
	from item_counts
	where item_rank <= 3
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Q10. What is the revenue contribution of each age group?