-- ============================================================================
-- Customer Shopping Behavior Analysis - SQL Queries
-- ============================================================================
-- Database: Customer Analytics
-- Table: customer (3,900 rows)
-- Purpose: Answer 10 key business questions via SQL aggregations
-- ============================================================================

-- ============================================================================
-- Q1. What is the total revenue generated by male vs. female customers?
-- ============================================================================
-- Purpose: Gender-based revenue segmentation for marketing targeting
-- Expected Output: 2 rows (Male, Female) with total revenue each

SELECT 
    gender,
    SUM(purchase_amount) as total_revenue,
    COUNT(*) as transaction_count,
    ROUND(AVG(purchase_amount), 2) as avg_transaction_value
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

-- ============================================================================
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
-- ============================================================================
-- Purpose: Identify high-value customers responsive to discounts
-- Expected Output: Customer IDs with above-average spend despite discount

SELECT 
    customer_id, 
    purchase_amount,
    item_purchased,
    discount_applied,
    ROUND((SELECT AVG(purchase_amount) FROM customer), 2) as avg_purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
    AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;

-- ============================================================================
-- Q3. Which are the top 5 products with the highest average review rating?
-- ============================================================================
-- Purpose: Identify best-performing products for recommendation & promotion
-- Expected Output: Top 5 products by average customer rating

SELECT TOP 5
    item_purchased,
    category,
    COUNT(*) as times_purchased,
    ROUND(AVG(review_rating), 2) as avg_review_rating,
    MIN(review_rating) as min_rating,
    MAX(review_rating) as max_rating
FROM customer
GROUP BY item_purchased, category
ORDER BY avg_review_rating DESC, times_purchased DESC;

-- ============================================================================
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
-- ============================================================================
-- Purpose: Analyze shipping method impact on order value
-- Expected Output: Average spend by shipping type

SELECT 
    shipping_type,
    COUNT(*) as order_count,
    ROUND(AVG(purchase_amount), 2) as avg_purchase_amount,
    ROUND(MIN(purchase_amount), 2) as min_amount,
    ROUND(MAX(purchase_amount), 2) as max_amount,
    SUM(purchase_amount) as total_revenue
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;

-- ============================================================================
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
--     between subscribers and non-subscribers.
-- ============================================================================
-- Purpose: Quantify subscription value for business strategy
-- Expected Output: Comparison of subscription vs. non-subscription metrics

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(CAST(purchase_amount AS numeric)), 2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue,
    ROUND(CAST(SUM(purchase_amount) AS numeric) / COUNT(*), 2) AS revenue_per_customer,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM customer), 2) AS customer_percentage
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- ============================================================================
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- ============================================================================
-- Purpose: Identify discount-dependent products for pricing strategy
-- Expected Output: Top 5 products by discount penetration rate

SELECT TOP 5
    item_purchased,
    category,
    COUNT(*) as total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) as discounted_purchases,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_rate_pct
FROM customer
GROUP BY item_purchased, category
ORDER BY discount_rate_pct DESC;

-- ============================================================================
-- Q7. Segment customers into New, Returning, and Loyal based on their total number 
--     of previous purchases, and show the count of each segment.
-- ============================================================================
-- Purpose: Customer lifecycle segmentation for targeted marketing
-- Expected Output: 3 segments with customer counts and metrics

WITH customer_segment_analysis AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END as customer_segment,
        SUM(purchase_amount) as lifetime_value,
        COUNT(*) as current_transactions
    FROM customer
    GROUP BY customer_id, previous_purchases
)
SELECT 
    customer_segment,
    COUNT(*) as segment_size,
    ROUND(AVG(CAST(lifetime_value AS numeric)), 2) as avg_lifetime_value,
    MIN(previous_purchases) as min_prev_purchases,
    MAX(previous_purchases) as max_prev_purchases,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(DISTINCT customer_id) FROM customer), 2) as segment_percentage
FROM customer_segment_analysis
GROUP BY customer_segment
ORDER BY avg_lifetime_value DESC;

-- ============================================================================
-- Q8. What are the top 3 most purchased products within each category?
-- ============================================================================
-- Purpose: Category-level product performance ranking
-- Expected Output: Top 3 products per category with sales metrics

WITH ranked_products AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) as total_orders,
        SUM(purchase_amount) as category_revenue,
        ROUND(AVG(purchase_amount), 2) as avg_item_price,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) as product_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    product_rank,
    category,
    item_purchased,
    total_orders,
    category_revenue,
    avg_item_price
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank;

-- ============================================================================
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) 
--     also likely to subscribe?
-- ============================================================================
-- Purpose: Analyze correlation between loyalty and subscription adoption
-- Expected Output: Subscription rate breakdown by buyer type

WITH buyer_classification AS (
    SELECT
        CASE 
            WHEN previous_purchases > 5 THEN 'Repeat Buyer (5+ purchases)'
            ELSE 'Occasional Buyer (<5 purchases)'
        END as buyer_type,
        subscription_status,
        COUNT(*) as customer_count,
        SUM(purchase_amount) as segment_revenue
    FROM customer
    GROUP BY buyer_type, subscription_status
)
SELECT 
    buyer_type,
    subscription_status,
    customer_count,
    segment_revenue,
    ROUND(100.0 * customer_count / SUM(customer_count) OVER (PARTITION BY buyer_type), 2) as subscription_rate_pct
FROM buyer_classification
ORDER BY buyer_type DESC, subscription_status DESC;

-- ============================================================================
-- Q10. What is the revenue contribution of each age group?
-- ============================================================================
-- Purpose: Demographic revenue analysis for targeted campaigns
-- Expected Output: Revenue breakdown by age brackets

WITH age_groups AS (
    SELECT
        CASE
            WHEN age BETWEEN 18 AND 25 THEN '18-25 (Gen Z)'
            WHEN age BETWEEN 26 AND 35 THEN '26-35 (Millennials)'
            WHEN age BETWEEN 36 AND 50 THEN '36-50 (Gen X)'
            WHEN age BETWEEN 51 AND 65 THEN '51-65 (Boomers)'
            ELSE '65+ (Senior)'
        END as age_bracket,
        purchase_amount,
        customer_id
    FROM customer
)
SELECT 
    age_bracket,
    COUNT(DISTINCT customer_id) as unique_customers,
    COUNT(*) as total_transactions,
    SUM(purchase_amount) as total_revenue,
    ROUND(AVG(purchase_amount), 2) as avg_transaction_value,
    ROUND(100.0 * SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer), 2) as revenue_contribution_pct
FROM age_groups
GROUP BY age_bracket
ORDER BY total_revenue DESC;

-- ============================================================================
-- END OF QUERIES
-- ============================================================================
